/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PatientPortalRouteImport } from './routes/patient-portal'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorsIndexRouteImport } from './routes/doctors.index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as DepartmentsSlugRouteImport } from './routes/departments.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientPortalRoute = PatientPortalRouteImport.update({
  id: '/patient-portal',
  path: '/patient-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsIndexRoute = DoctorsIndexRouteImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/departments/$slug',
  path: '/departments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointment': typeof AppointmentRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/laboratory': typeof LaboratoryRoute
  '/packages': typeof PackagesRoute
  '/patient-portal': typeof PatientPortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointment': typeof AppointmentRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/laboratory': typeof LaboratoryRoute
  '/packages': typeof PackagesRoute
  '/patient-portal': typeof PatientPortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/departments': typeof DepartmentsIndexRoute
  '/doctors': typeof DoctorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/appointment': typeof AppointmentRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/emergency': typeof EmergencyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/laboratory': typeof LaboratoryRoute
  '/packages': typeof PackagesRoute
  '/patient-portal': typeof PatientPortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/departments/': typeof DepartmentsIndexRoute
  '/doctors/': typeof DoctorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/appointment'
    | '/careers'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/gallery'
    | '/laboratory'
    | '/packages'
    | '/patient-portal'
    | '/sitemap.xml'
    | '/departments/$slug'
    | '/departments/'
    | '/doctors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/appointment'
    | '/careers'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/gallery'
    | '/laboratory'
    | '/packages'
    | '/patient-portal'
    | '/sitemap.xml'
    | '/departments/$slug'
    | '/departments'
    | '/doctors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/appointment'
    | '/careers'
    | '/contact'
    | '/emergency'
    | '/faq'
    | '/gallery'
    | '/laboratory'
    | '/packages'
    | '/patient-portal'
    | '/sitemap.xml'
    | '/departments/$slug'
    | '/departments/'
    | '/doctors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppointmentRoute: typeof AppointmentRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EmergencyRoute: typeof EmergencyRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  LaboratoryRoute: typeof LaboratoryRoute
  PackagesRoute: typeof PackagesRoute
  PatientPortalRoute: typeof PatientPortalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
  DoctorsIndexRoute: typeof DoctorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-portal': {
      id: '/patient-portal'
      path: '/patient-portal'
      fullPath: '/patient-portal'
      preLoaderRoute: typeof PatientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/': {
      id: '/doctors/'
      path: '/doctors'
      fullPath: '/doctors/'
      preLoaderRoute: typeof DoctorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/departments/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppointmentRoute: AppointmentRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EmergencyRoute: EmergencyRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  LaboratoryRoute: LaboratoryRoute,
  PackagesRoute: PackagesRoute,
  PatientPortalRoute: PatientPortalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DepartmentsSlugRoute: DepartmentsSlugRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
  DoctorsIndexRoute: DoctorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
